# Generated by Django 6.0.2 on 2026-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=10)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
