# Generated by Django 6.0.2 on 2026-03-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyTransaction',
        ),
    ]
