# Generated by Django 6.0.2 on 2026-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_delete_companytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
