# Generated by Django 6.0.2 on 2026-03-17 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_companyaccount_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttracking',
            name='matured_at',
        ),
        migrations.AddField(
            model_name='investmenttracking',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmenttracking',
            name='invested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
