# Generated by Django 6.0.2 on 2026-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='invested_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
