# Generated by Django 6.0.2 on 2026-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_companyaccount_invested_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
