# Generated by Django 6.0.2 on 2026-05-19 09:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_ledgerentry_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttracking',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.03'), max_digits=5),
        ),
    ]
