# Generated by Django 6.0.2 on 2026-03-18 09:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_investmenttracking_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
