# Generated by Django 6.0.4 on 2026-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_ledgerentry_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
