# Generated by Django 6.0.2 on 2026-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_companyaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_request_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='originator_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
