# Generated by Django 6.0.2 on 2026-03-18 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_transaction_merchant_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttracking',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmenttracking',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.005'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
