# Generated by Django 6.0.2 on 2026-03-19 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_investmenttracking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttracking',
            name='maturity_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 20, 13, 21, 56, 266626, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
